### ISSUE TITLE
Support 32-bit Thumb instruction

### ISSUE THREAD

**Issue by wildlarva** [wildlarva/mcdecoder#14]
**Is your feature request related to a problem? Please describe.**
An ARM 32-bit Thumb instruction consist of two 16-bit words. This is stored differently from an ARM 32-bit ARM instruction in little endian environment. mcdecoder doesn't support it.

In a little endian environment, a 4-byte word(b4 b3 b2 b1) is stored in memory like below:
- 32-bit ARM instruction: b1 b2 b3 b4 (stored as one 4-byte word)
- 32-bit Thumb instruction: b3 b4 b1 b2 (stored as two 2-byte words)

**Describe the solution you'd like**
Extend the encoding format of MC description to express and support 32-bit instruction of two 16-bit words.

Example(the symbol '||' expresses the boundary between 16-bit words):
```yaml
instructions:
  - ...
    format: xxxx:cond|00|1|0100|x:S|xxxx:Rn || xxxx:Rd|xxxx xxxx xxxx:imm12
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A
